# https://github.com/microsoft/vscode-remote-try-node/blob/2707155e8d1b6a4265c1b3ded5777c6c508356a0/.devcontainer/Dockerfile#L3-L4
ARG VARIANT=16-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}
